### ISSUE TITLE
OSI with projection are not working on simple examples

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#130]
Hi,

The schemes MoreauJeanDirectProjectionOSI and MoreauJeanCombinedProjectionOSI are not working anymore on simple examples such as BouncingBallTS-ProjectOnConstraints.cpp or BouncingBallTS-CombinedProjection.cpp.

It seems that the projection is not performed correctly and the maximum number of iterations is reached.

Any idea ?

**Comment by vacary** [comment]
FYI,

The schemes were working well after the commit 450edda690580b4fa3f5dd837e5cbaf2df870ed3 
I will start a git bissect to know where it has started to fail.

**Comment by vacary** [comment]
result:
```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
5a8f3d50540a43d13d27474aea4f8fff8a85361e
88d09f622d6b52f91e232186d6bd47caf4c537b6
b62dd92e8e4c7271f791978b06147093dbd2a4da
We cannot bisect more!
bisect run cannot continue any more
```

**Comment by radarsat1** [comment]
I can confirm that it is broken after 5a8f3d50540a43d13d27474aea4f8fff8a85361e and not before.

**Comment by radarsat1** [comment]
That commit is too big, I can't tell what changes are important.  Much of it is renaming and whitespace changes, but they are mixed with changes to variable initialization and some computational stuff.

We have to eliminate possibilities one by one.  I would expect mistakes in variable initialization to lead to segfaults, but possibly something uninitialized could go unnoticed.  Otherwise, the other possibility is something updating at the wrong place.  I see the following possible effects that could be related to BouncingBallTS-CombinedProjection.cpp:

- [ ] changes to mass matrix handling (init/update_inverse_mass)
- [ ] changes to normRef, which is no longer saved in the DS
- [ ] could it have something to do with FirstOrderLinearDSTest::testBuildFirstOrderLinearDS1 failure?  (ds->rhs()) == tmp fails)
- [ ] there are a few changes to where swapInMemory() is called

**Comment by radarsat1** [comment]
Here is the difference with the ref (position)
![figure_1-4](https://cloud.githubusercontent.com/assets/66805/25823399/62681bae-3412-11e7-90a2-451d385c4b86.png)

**Comment by vacary** [comment]
I fixed the issue for MoreauJeanDirectProjectionOSI at least for example BouncingBallTS-ProjectOnConstraints.cpp in 86090cc0345e71792d2b9bad6b921513fb24dc4f

The insertion of the multiplier p(0) in DSLINK was not done.

It remains to do the same thing for the other projection schemes.

By the way, the creation, initialization and insertion of p is a little bit messy.

**Comment by radarsat1** [comment]
Very nice! I feel like some of this fill_ds_links stuff could be reduced to a more declarative method.. it seems every OSI repeats the same logic but with slight differences. Anyways, no specific ideas yet..

**Comment by vacary** [comment]
Yes, It would nice to factorize the code, but I do not where we can do that
