### ISSUE TITLE
Work vectors and matrices in FirstOrderR

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#148]
After finalizing the clean-up of the Interaction class, we should think to the organisation of the relation, especially, for the First Order Relations.

In [FirstOrderR](https://github.com/siconos/siconos/blob/master/kernel/src/modelingTools/FirstOrderR.hpp) class, we find:
`  enum FirstOrderRVec {osnsp_rhs,vec_z, vec_x, vec_r, e, h_alpha, g_alpha, vec_residuY, vec_residuR, workVecSize};
  enum FirstOrderRMat {mat_C, mat_D, mat_F, mat_B, mat_K, mat_Ktilde, mat_Khat, mat_workMatSize};
 `
A part of the work buffers described by these enum are used by the OSI in various situations (vec_residuR, vec_residuY, g_alpha, ...). They should be declares directly in the OSI as we have done for the work buffers related to the DynamicalSystem.

In that present case, another part of this work buffers is directly used in the modeling part. (e, mat_C, mat_D, mat_F, mat_B, mat_K, etc ....). Perhaps we should split the two types of work buffers or to remove by using directly attributes: _e, _C, _D, _F, _B, _K, 

For instance,  in [FirstOrderNonLinearR](https://github.com/siconos/siconos/blob/master/kernel/src/modelingTools/FirstOrderNonLinearR.hpp) we have
`  if (_D)
    prod(*_D, *(inter.lambdaOld(level)), y, true);
  else
    prod(*workM[FirstOrderR::mat_D], *(inter.lambdaOld(level)), y, true);`

Is there any reason for using `workM[FirstOrderR::mat_D]` rather directly _D ?

For vectors, I see an interest of using workV for instance in 
`SiconosVector& x = *workV[FirstOrderR::vec_x];
  x = *DSlink[FirstOrderR::x];
  SiconosVector& z = *workV[FirstOrderR::vec_z];
  z = *DSlink[FirstOrderR::z];
  computeg(time, x, *inter.lambda(level), z, g_alpha);
  *DSlink[FirstOrderR::z] = z;`
since we need continuous memory for calling plug-in.

In that case, It should be better to split Work vectors and to add working buffer in FirstOrderR as attributes.

What do you think ?

**Comment by xhub** [comment]
The rational for if (_D) ... comes from the fact that the presence of a matrix as an attribute implies that this quantity is constant. The test ``if (_D)'' is used in the control flow to determine whether a call for a computation of a quantity is needed. 

We can change this and have a vector of booleans _isConstantsData[] that can be used to the same effect. Then the storage of the data could be move to the graph or kept in the Relation.

I would be against that move for the following reason: right now we have (or should have) a good separation between modeling and simulation data. All the attribute of a relation should be constant and all the data in the graph are the result of computations. That way we could use an relation in multiple interaction, or have multiple simulations running in parallel using the same modeling objects.

We could move everything to the graph, but copy the pointer instead of allocating a new matrix when we want to reuse a relation. I like the idea of moving most of the data to the graph rather than attributes. It limits the side effects when calling methods, and it is easier to see (via the function signature) what that function is operating on.

**Comment by xhub** [comment]
How much of this is still current given the recent changes?

**Comment by vacary** [comment]
fixed in 53edc7e
