### ISSUE TITLE
Remaining tests that fail

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#157]
List of test that fails to today:

fc3d__NSGS_NCPGlockerFBNewton_Tol_1e16_Max_1000_inTol_0_inMax_0_Example1_Fc3D_SBM__EXPECTED_TO_FAIL

FirstOrderLinearDSTest::testBuildFirstOrderLinearDS1

gfc3d_SICONOS_GLOBAL_FRICTION_3D_NSN_AC_Tol_0_Max_0_inTol_0_inMax_0_problem-check	

LagrangianLinearTIDSTest::testBuildLagrangianLinearTIDS1

NCP_NEWTON_FBLSA-NCP_ZI1	

python_test_dynamical_systems,	

python_test_Kernel,

python_test_xml,

test-LCP_NEWTONMIN-lcp_CPS_4

test-LCP_NEWTONMIN-lcp_CPS_4bis

test-LCP_NEWTONMIN-lcp_enum_fails

Who will do what ?

**Comment by radarsat1** [comment]
Depends on #131 and #132.

**Comment by xhub** [comment]
I'll take
- test-LCP_NEWTONMIN-lcp_CPS_4
- test-LCP_NEWTONMIN-lcp_CPS_4bis
- test-LCP_NEWTONMIN-lcp_enum_fails

**Comment by xhub** [comment]
I'll take the following:
- NCP_NEWTON_FBLSA-NCP_ZI1
- test-LCP_NEWTONMIN-lcp_CPS_4
- test-LCP_NEWTONMIN-lcp_CPS_4bis
- test-LCP_NEWTONMIN-lcp_enum_fails

**Comment by fperignon** [comment]
> Le 20 juin 2017 à 16:34, Vincent Acary <notifications@github.com> a écrit :
> 
> List of test that fails to Today:
> 
> fc3d__NSGS_NCPGlockerFBNewton_Tol_1e16_Max_1000_inTol_0_inMax_0_Example1_Fc3D_SBM__EXPECTED_TO_FAIL
> 
> gfc3d_SICONOS_GLOBAL_FRICTION_3D_NSN_AC_Tol_0_Max_0_inTol_0_inMax_0_problem-check
> 


> 


FirstOrderLinearDSTest::testBuildFirstOrderLinearDS and LagrangianLinearTIDSTest::testBuildLagrangianLinearTIDS1
work fine for me. Sounds like accuracy error depending on the compiler or something like this. I’ll check that.

> NCP_NEWTON_FBLSA-NCP_ZI1
> 
> python_test_dynamical_systems,
> 

This test fails because of NewtonEulerDS does not respect the DS global interface : rhs() is missing. This is a side effect of lazy/delayed initialisation of class operators:

for all DS:
- rhs() returns _x[1]
- _x[1] is not None (Null) if and only if ds.initRhs() has been called previously (as in the test)

So to fix, initRhs must be implemented properly in NewtonEulerDS to  fit with the spec above.
But maybe it’s quite useless to deal with rhs() in NewtonEulerDS, in that case, to fix the test we should remove ‘NewtonEulerDS’ from ds_classes dict in test_dynamical_systems. What do you think? 

> python_test_Kernel,
> 

fails because, v being a SiconosVector,
 zip(v, …) or list(v) are not allowed.
Steve, are these operations supposed to work?? Don’t think so

**Comment by radarsat1** [comment]
> >  python_test_Kernel,
> fails because, v being a SiconosVector,
>  zip(v, …) or list(v) are not allowed.
> Steve, are these operations supposed to work?? Don’t think so

Yes!  I added that, it should work.  However, this test isn't failing for me locally, and curiously I don't see it on c-dash for 2017-06-20 but i do see it for  2017-06-19..  it must be only certain configurations, I'll try to figure that out.

**Comment by radarsat1** [comment]
I was just running tests locally in a 17.04 docker container, missing in this list is 
> 824 - KernelTest::t8 (Failed)
> 810 - python_test_serialization, (SEGFAULT)

**Comment by fperignon** [comment]
https://github.com/siconos/siconos/commit/f58baec64e602a4f7887926490467407e4892e84 Fix 
FirstOrderLinearDSTest::testBuildFirstOrderLinearDS1
LagrangianLinearTIDSTest::testBuildLagrangianLinearTIDS1
Just changed tolerance in vector/matrices comparison using classical rtol/atol parameters


https://github.com/siconos/siconos/commit/41952bf98abe6638d48b9f19ceee81966c7c8a7b
Fix test_xml (python) : add missing link between simu and nsds.

**Comment by fperignon** [comment]
Steve, concerning python_test_Kernel, you told it works for you. Which python version did you used?
I tried it with python27 --> ok
python36 --> no!

**Comment by radarsat1** [comment]
Yes I'm still trying to reproduce. I'm copying the cmake configuration from [this cdash test](http://cdash-bipop.inrialpes.fr/viewTest.php?onlyfailed&buildid=26470) but still not getting it.  However, in-progress.  I'll try again with Python 3.  I've got a couple of versions of Ubuntu to go.. (I've tested with 14.04 and 17.04 but not yet 16.04, although that's what I use locally and still don't see it..)  I'll will post an update soon.

**Comment by radarsat1** [comment]
Yeah I really don't understand.. result so far:

~~~
root@tracktek:~/build/wrap/siconos/tests# python3 ../../runtests.py test_Kernel.py 
================================== test session starts ==================================
platform linux -- Python 3.4.3, pytest-2.8.7, py-1.4.31, pluggy-0.3.1
rootdir: /root/build/wrap, inifile: 
collected 8 items 

test_Kernel.py ........

=============================== 8 passed in 0.22 seconds ================================
~~~

I will keep trying.

**Comment by radarsat1** [comment]
@fperignon I've tried with 3 versions of Ubuntu, release/build, python2/3, and can't get this test to fail. Can you tell me what line it is failing on and maybe paste the output here?

**Comment by radarsat1** [comment]
It seems the test_Kernel.py is no longer failing on recent c-dash builds.
Apart from numerics failures, that leaves only test_dynamical_systems.py.
To reiterate @fperignon's analysis, the problem is that NewtonEulerDS does not have rhs(), i.e., `_x` defined.  Looking at the definitions for LagrangianDS, x=[q qdot], then isn't it in the NE case the same, that is, x = [q v], so x should be a SiconosVector of size 7+6=13.  Is that correct?

**Comment by vacary** [comment]
*  fc3d__NSGS_NCPGlockerFBNewton_Tol_1e16_Max_1000_inTol_0_inMax_0_Example1_Fc3D_SBM__EXPECTED_TO_FAIL

* gfc3d_SICONOS_GLOBAL_FRICTION_3D_NSN_AC_Tol_0_Max_0_inTol_0_inMax_0_problem


are now fixed

What remains ?

**Comment by vacary** [comment]
Here is the updated list on [cdash](https://cdash-bipop.inrialpes.fr/viewTest.php?onlyfailed&buildid=26609)


|gfc3d__NSGS_NCPGlockerFBNewton_Tol_1e-16_Max_1000_inTol_0_inMax_0_Example1_Fc3D_SBM__EXPECTED_TO_FAIL | Failed | 200ms | Completed (OTHER_FAULT) |  
-- | -- | -- | -- | --
gfc3d_SICONOS_GLOBAL_FRICTION_3D_NSN_AC_Tol_0_Max_0_inTol_0_inMax_0_problem-check | Failed | 10ms | Completed (Failed) |  
NCP_NEWTON_FBLSA-NCP_ZI1 | Failed | 15s | Completed (Timeout) |  
test-LCP_NEWTONMIN-lcp_CPS_4 | Failed | 10ms | Completed (Failed) |  
test-LCP_NEWTONMIN-lcp_CPS_4bis | Failed | 10ms | Completed (Failed) |  
test-LCP_NEWTONMIN-lcp_enum_fails

**Comment by vacary** [comment]
I remove fc3d__NSGS_ONECONTACT_NSN_GP_Tol_1e-5_Max_100000_inTol_0_inMax_0_BoxesStack1-i100000-32.hdf5__EXPECTED_TO_FAIL that either is not able to converge or is in timeout.

The behavior is logical.

**Comment by vacary** [comment]
I suggest to close the issue and to open new issues for 
ZOHTest::testMatrixExp*
test-LCP_NEWTONMIN-lcp_*
EigenProblemsTest::testGeev1
in milestones 4.2
