### ISSUE TITLE
Failed examples (for 4.1)

### ISSUE THREAD

**Issue by xhub** [siconos/siconos#179]
Examples that fails for 4.1. List based on http://cdash-bipop.inrialpes.fr/viewTest.php?onlyfailed&buildid=26952

Causes include: missing files, missing dependency (OCC, ...), and bugs. Feel free to make the test not run.

- [ ] BulletBouncingBox_BulletBouncingBox
- [ ] BulletBouncingBox_BulletBouncingBoxDynamic
- [ ] BulletBouncingBox_BulletBouncingBoxDynamic_py
- [ ] BulletBouncingBox_BulletBouncingBox_py
- [ ] DirectProjection_cube_directproj_py
- [ ] DirectProjection_doublePendulum_directproj_py
- [ ] DirectProjection_n_cubes_directproj_py
- [ ] GeometricPrimitives_box_stacks_py
- [ ] GeometricPrimitives_convexhull_py
- [ ] GeometricPrimitives_cube_simulation_py
- [ ] GeometricPrimitives_cylinder_py
- [ ] GeometricPrimitives_mesh_py
- [ ] GeometricPrimitives_reused_cube_py
- [ ] GeometricPrimitives_sphere_clusters_py
- [ ] GeometricPrimitives_tetra_py
- [ ] GranularMaterial_chute_con_rocas_y_vibradores_py
- [ ] ImpactingBar_ImpactingBar
- [ ] InterestingDynamics_doublePendulum_py
- [ ] InterestingDynamics_moving_block_py
- [ ] InterestingDynamics_MultipleContactorsAndNSlaws_py
- [ ] InterestingDynamics_slide_roll_py
- [ ] InterestingDynamics_tippe_top_py
- [ ] InterestingDynamics_walker_py
- [ ] JointsTestsWithBoundaryConditions_NE_3DS_3Knee_1Prism_GMP
- [ ] JointsTestsWithContactDetection_Joint_stops_py
- [ ] Music_run_py
- [ ] NewtonEuler_BouncingBallNE-MoreauJeanGOSI
- [ ] NewtonEuler_BouncingBallNETS_py
- [ ] NewtonEuler_FastSpinningObjects_py
- [ ] OCC_Examples_occ_balls_in_a_bowl_py
- [ ] OCC_Examples_occ_bouncing_ball_py
- [ ] OCC_Examples_occ_double_pendulum_py
- [ ] OCC_Examples_occ_slider_crank_py
- [ ] OptimalControl_OptimalControl
- [ ] RigidBodiesCollection_n_cubes_py
- [ ] RigidBodiesCollection_n_cubes_simulation_py
- [ ] RockFall_cubes_sphere_contactors_py
- [ ] RockingBlock_RockingBlockED_NewMarkAlpha
- [ ] SMC_SMCExampleExplicit
- [ ] SMC_SMCExampleImplicit
- [ ] SMC_SMCExampleImplicitOT2
- [ ] StepSystem_StepSystem
- [ ] Zhuravlev_ZhuravlevIvanovMCP_py
- [ ] Zhuravlev_ZhuravlevIvanovVI_py

**Comment by radarsat1** [comment]
Many are ref files that need investigating / updating.  (The BouncingBox ones are known..)

In the case of some Python failures with matplotlib, I guess the examples need to skip the plotting code in case that there is no display.

The OCC examples fail because OCC is not configured I think.  (e.g., "ImportError: No module named OCC.BRepPrimAPI")

Some of these tests end with, e.g.,

> The rest of the test output was removed since it exceeds the threshold of 307200 bytes.

What's the command to use to run all the examples locally?

It would be nice if there was a way to distinguish easily between failures due to ref files and failures due to segfaults for example.

**Comment by xhub** [comment]
I believe you run ``cmake siconos/example'', but you may need to tweak some env var or cmake option so that it can find your siconos install.

For matplotlib there is this code in some examples:
import matplotlib,os
havedisplay = "DISPLAY" in os.environ
if not havedisplay:
    matplotlib.use('Agg')


That appear to be sufficient for Unix-based systems

**Comment by radarsat1** [comment]
Here's my run,

~~~
mkdir ex
cd ex
cmake ../siconos/examples
make
ctest
~~~

output is:
~~~
The following tests FAILED:
          5 - StepSystem_StepSystem (Failed)
         20 - ImpactingBar_ImpactingBar (Failed)
         23 - JointsTestsWithBoundaryConditions_NE_3DS_3Knee_1Prism_GMP (Failed)
         47 - NewtonEuler_BouncingBallNE-MoreauJeanGOSI (Failed)
         59 - BulletBouncingBox_BulletBouncingBoxDynamic (Failed)
         60 - BulletBouncingBox_BulletBouncingBox (Failed)
         66 - FourBarLinkageWith3clearance_FourBarClearance (Timeout)
         68 - ColumnOfBeads_ColumnOfBeadsTS-SBM (Failed)
         81 - RockingBlock_RockingBlockED_NewMarkAlpha (Failed)
         98 - OptimalControl_OptimalControl (Failed)
        100 - TwoLinkManipulator_Two-linkMulticonstrManip (Timeout)
        101 - TwoLinkManipulator_TwolinkMultiFlex (Timeout)
        104 - SMC_SMCExampleExplicit (Failed)
        106 - SMC_SMCExampleImplicitOT2 (Failed)
        107 - SMC_SMCExampleImplicit (Failed)
~~~

I'll try to take a look at most of these soon.  I am away next week unfortunately.  I examined a few, it seems BulletBouncingBox has reference file problems.  (The dynamics of BulletBouncingBox are a little crazy..)

FourBarLinkageWIthClearance is a plugin loading problem, it works when I run it by setting `LD_LIBRARY_PATH=.`

NE_3DS_3Knee_1Prism_GMP is a plugin problem *and* a reference file problem.  Maybe due to changing the joint references, I'll check on that. ImpactingBar and ColumnsOfBeadsTS-SBM are indeed reference file mismatches.

RockingBlockED-NewMarkAlpha is a plugin loading problem, but on running it with LD_LIBRARY_PATH, it crashes with
~~~
A new event occurs at time: 4.882813e-07
Runtime Exception : NewMarkAlphaOSI::computeFreeOutput, this OSNSP does not exist
~~~

**Comment by vacary** [comment]
Hi,

There are 5 examples that fail :
https://cdash-bipop.inrialpes.fr/viewTest.php?onlyfailed&buildid=28120

Two are important since they are clearly the results of our recent (or old) modifications:
 - RockingBlock_RockingBlockED_NewMarkAlpha 
 - StepSystem_StepSystem
The other issues are very simple to solve.

I am working on RockingBlock_RockingBlockED_NewMarkAlpha the problem comes from the new initialization of the osi.

For StepSystem_StepSystem, the example is broken since two years. I think we can release without fixing it and put it into known issues.

The most important thing for the release is not to succeed to pass all the examples but writing the ChangeLog. If some examples are still failing, we will indicate in the "known issues" section.

**Comment by bremond** [comment]
>There are 5 examples that fail :
>https://cdash-bipop.inrialpes.fr/viewTest.php?onlyfailed&buildid=28120

Yesterday, I set Jenkins to build 4.1.x branch with the master on
siconos---vm3.ci, the host which build examples. 4.1.x is in the state
we leave it at the beginning of the summer and it is nearly releasable.

They are also a few tests that fails, but depending on the config they
are not the same.

I do not understand why the master examples have not been built at the
same time (Siconos-with_umfpack-Release-Linux-x86_64 is the only config
it have builded, why? I am really fed up with Jenkins), but
anyway, for comparison the latest ones to have been built, the day
before, are there:
http://cdash-bipop.inrialpes.fr/viewTest.php?onlyfailed&buildid=28113

many regressions, but it is another story.
