### ISSUE TITLE
Coupling NewtonEulerDS with nonlinear links (spring, dashpot, ...)

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#185]
Following the @radarsat1 's comment in commit 25d3411705244dd070da9f17dd7d56b273c57496 , I open a new issue on the coupling between NewtonEulerDS.

The most simple example is when we want to add a linear spring between to NewtonEulerDS. Since the dynamics of NewtonEulerDS is highly non linear, a spring coupling between  two NewtonEulerDS results in a nonlinear system that could be implemented in two manners:
- Either we add some linear or nonlinear equality constraints between DS and we treat it as an interaction in the GenericalMechanicalProblem of Numerics. For springs, we need to treat at the position level as is is partly done in the compliant relation [LagrangianCompliantR](https://github.com/siconos/siconos/blob/master/kernel/src/modelingTools/LagrangianCompliantR.hpp). 
- The other way is to take into account coupling through internal forces in NewtonEulerDS. We did that for the C60 mechanism by adding some internal forces between two DS linked by springs. For the moment, this approach is not satisfactory since the computation of the forces in the link is based on the current value of the current position of the DS and it is updated in the Newton loop in a explicit way. Therefore, the Newton loop is converging slowly. If we want to go further, the Jacobian matrices corresponding to this coupling must be taken into account. In the current implementation it is not possible since they appears as extra diagonal blocks w.r.t to DS in the complete W matrix. 

My question is : should we implement a new class that couples two NewtonEulerDS to be able to build a complete W matrix for these system ?

**Comment by radarsat1** [comment]
Yes, I wasn't sure what to do there. I was curious about implementing the gear ratio as a kind of "relation between two relations", but then discovered that the ODE implementation works more like a single relation that has a "reference body", which was much easier to implement.

In my implementation, this reference is just the pointer to the SiconosVector q() of the body.  However, technically this is like a third outgoing edge of the interaction, and it would be better to represent it somehow in the graph.  It should be connected to the Newton loop's work vector associated with the reference body.  (This should actually be possible by passing the right SP::SiconosVector, but this pointer is not public afaik.)

In practice it seems to work fine, but at large timesteps it appears to cause oscillatory behaviour in some cases.

The whole idea of relations based on other relations is very fun to play with, as you can design constraints within the manifold of other constraints, however I realized lately that there are some conceptual obstacles.  For instance, JointFrictionR::computeJachq() calls the reference joint's computeJachq(), however it passes the wrong Interaction pointer.  In practice this doesn't matter, since the Joint does not use that parameter, however conceptually it is incorrect.

**Comment by vacary** [comment]
Transferred in https://github.com/siconos/siconos/wiki/Wish-list-and-enhancement
