### ISSUE TITLE
Update SuiteSparse/CSparse

### ISSUE THREAD

**Issue by radarsat1** [siconos/siconos#189]
Siconos contains an old version of CSparse which limits our ability to integrate with existing packages on e.g. Debian/Ubuntu-based installations.  Upgrading to a more recent version of the interface would be a step towards reducing the number of things in "externals".

**Comment by xhub** [comment]
I now have those issues when using the internal copy of SuiteSparse:

The first one is not too bad:

In file included from /home/xhub/siconos-tmp/externals/SuiteSparse/CSparse_extensions/SparseMatrix_internal.h:47:0,
                 from /home/xhub/siconos-tmp/numerics/src/tools/NM_SuperLU.c:23:
/home/xhub/siconos-tmp/externals/SuiteSparse/CXSparse/cs.h:689:0: warning: "csn" redefined
 #define csn CS_NAME (n)
 
In file included from /home/xhub/siconos-tmp/numerics/src/tools/NumericsMatrix.h:126:0,
                 from /home/xhub/siconos-tmp/numerics/src/tools/NumericsMatrix_internal.h:27,
                 from /home/xhub/siconos-tmp/numerics/src/tools/NM_SuperLU.c:20:
/home/xhub/siconos-tmp/externals/SuiteSparse/CSparse_extensions/SparseMatrix.h:78:0: note: this is the location of the previous definition
 #define csn cs_dln
 

The second one is really bad:


In file included from /home/xhub/siconos-tmp/externals/SuiteSparse/CXSparse/cs.h:52:0,
                 from /home/xhub/siconos-tmp/externals/SuiteSparse/CSparse_extensions/SparseMatrix_internal.h:47,
                 from /home/xhub/siconos-tmp/numerics/src/tools/NM_SuperLU.c:23:
/home/xhub/siconos-tmp/externals/SuiteSparse/CXSparse/SuiteSparse_config.h:85:8: error: redefinition of ‘struct SuiteSparse_config_struct’
 struct SuiteSparse_config_struct
        ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/umfpack.h:29:0,
                 from /home/xhub/siconos-tmp/numerics/src/tools/NumericsMatrix_internal.h:87,
                 from /home/xhub/siconos-tmp/numerics/src/tools/NM_SuperLU.c:20:
/usr/include/SuiteSparse_config.h:85:16: note: previous definition of ‘struct SuiteSparse_config_struct’
 typedef struct SuiteSparse_config_struct

So I have umfpack installed systemwide, which requires Suitesparse_config. Now the funny thing is that they changed the macro defined in SuiteSparse_config.h:

_SUITESPARSECONFIG_H vs SUITESPARSE_CONFIG_H

This is just a notice that it is more of a mess than we (I?) though. I rework the detection of the systemwide suitesparse so that now it doesn't use the internal one

**Comment by radarsat1** [comment]
How can I reproduce it?

On my system (Ubuntu 17.04) I have libumfpack installed system wide and the headers are installed via libsuitesparse-dev, and I do not have these errors.  Can you give me your system details?  How did you install UMFPACK?  For my the header appears in `/usr/include/suitesparse/umfpack.h`, so it must be installed differently.

Ah, I think I see.. you are using the internal CXSparse but trying to use it with an external UMFPACK.

But UMFPACK comes with SuiteSparse.  I guess it would be better to force the user to always be consistent with the versions of UMFPACK and CXSparse.  Using a UMFPACK from a different version of SuiteSparse is maybe asking for trouble.  When using the internal CXSparse, we should also use an internal UMFPACK.  I guess that implies including UMFPACK in externals.

Just to be clear, does it work when you use the system-installed CXSparse?

**Comment by xhub** [comment]
Sorry I should have been more precise. I have a gentoo distro. My systemwide UMFPACK needs suitesparse. Hence, I have suitesparse (version 4.2.1) system wide. The detection of the systemwide suitesparse did not work on my setup. I believe that I fixed it (the scope of the cmake variable USE_SYSTEM_SUITESPARSE was local and so it was not set in external/). When I modified it, it worked on my setup with a systemwide suitesparse. I just made that comment to highlight that we may run into some issues if two versions of suitesparse are mixed. This is a bad decision made during the development of suitesparse to change the value of the include guard. We may wanna enforce USE_SYSTEM_SUITESPARSE with WITH_UMFPACK.

**Comment by radarsat1** [comment]
Just noting that I added CXSparse_LIBRARY back to SICONOS_LINK_LIBRARIES in this commit: https://github.com/siconos/siconos/commit/7bdb07d88db557d0af72c3f2e76e4c8fd5727790

Otherwise it doesn't link the system-wide cxsparse.  I hope it doesn't break things for you.

I think in general I prefer that if a system-wide suitesparse is requested, it's better for CMake to fail than for it to default to the built-in one, but that's just an opinion.  In any case, if there is a possibility that SuiteSparse cs.h is not found by the standard find_path/find_library commands, then it should be possible for you to specify it with `-DCXSparse_INCLUDE_DIR=...`

At least, we should make sure that works.

**Comment by radarsat1** [comment]
By the way if you have any kind of Dockerfile that can help me reproduce your Gentoo setup I can try to use it during testing to make sure not to break things in the future.  In general I have been assuming that Linux == Debian but I know that's not generally true and I should be testing on more platforms.

**Comment by xhub** [comment]
Gentoo is a niche distro that requires to build everything from source. I don't know how hard it would be to create a docker image and whether it's worth it. I appreciate the intention :)
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by xhub** [comment]
* Stephen Sinclair <notifications@github.com> [2017-12-12 14:22:50 +0000]:

> Just noting that I added CXSparse_LIBRARY back to SICONOS_LINK_LIBRARIES in this commit: https://github.com/siconos/siconos/commit/7bdb07d88db557d0af72c3f2e76e4c8fd5727790
> 
> Otherwise it doesn't link the system-wide cxsparse.  I hope it doesn't break things for you.

On my setup there is no need for that (system-wide cxsparse). The variable SuiteSparse_LIBRARIES is added to the list of library in by the compile_with macro (cmake/SiconosTools.cmake, l. 197). I don't understand why it is needed on your setup. My version of cmake is 3.10.0. Could you see what does not work on the setup you experience the issue? SuiteSparse_LIBRARIES is set to CXSparse_LIBRARY in cmake/FindSuiteSparse.cmake.

**Comment by radarsat1** [comment]
Ah ok, maybe I missed something, I'll take a closer look to verify.  Thanks.

**Comment by xhub** [comment]
Any updates :) ? I still see 
```
list(APPEND SICONOS_LINK_LIBRARIES ${CXSparse_LIBRARY})
```
in cmake/siconos_find_common_dep.cmake.

**Comment by radarsat1** [comment]
Hm, don't know it's been a while.  I removed the line and rebuilt and it does link to the system cxsparse.  So I pushed a revert on that patch.
