### ISSUE TITLE
Build failed with bullet

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#19]
Unable to compile bullet's swig interface in Siconos [33d75579](33d755797959169500e4d1e464a7c57af5fa8794). The following Bullet version is used[de3b6c31c](de3b6c31c1451df6a8107b6e2a8683c736cef126) but the problem exists still the versions 2.82.
It seems that something is wrong in the inclusion of the header file of bullet in [bullet.i](https://github.com/siconos/siconos/blob/master/mechanics/swig/mechanics/contact_detection/bullet.i)

[make_output.txt](https://github.com/siconos/siconos/files/169070/make_output.txt)

**Comment by xhub** [comment]
This commit https://github.com/siconos/siconos/commit/b046333568ccb3506c1bf548f015daf479dcac91 breaks the build on our CI machine, cf http://cdash-bipop.inrialpes.fr/viewBuildError.php?buildid=18001 and also the ubuntu packages, cf https://launchpadlibrarian.net/247620074/buildlog_ubuntu-xenial-i386.siconos_3.9~alpha-0~4864~ubuntu16.04.1_BUILDING.txt.gz

I guest that the version of bullet that you use is https://github.com/bulletphysics/bullet3/commit/de3b6c31c1451df6a8107b6e2a8683c736cef126 

It looks like the issue is with a change in the bullet header. Can you test with a release version ? It's working fine here with 2.83.5 and it was working for ubuntu on 2.83.6

**Comment by xhub** [comment]
I've submitted a tentative fix, if it does work, you can revert it locally

**Comment by vacary** [comment]
In fact, I had the same problem with the package version 2.82 or 2.83.7 or directly from the github master branch. It works now like a charm. Thanks.

I have to understand the difference between import and include.
