### ISSUE TITLE
occ_slider_cranck.py is not working

### ISSUE THREAD

**Issue by bremond** [siconos/siconos#217]
bf5a9f2a0 makes it runnable after changes in master but the solver fails to find some correct solutions at the second iteration. It was already broken after a rebase (https://github.com/bremond/siconos/tree/mechanics-occ-rebase) that I did before the final merge in master (PR #193).

it works in this branch https://github.com/bremond/siconos/tree/mechanics-occ before the rebase.

**Comment by bremond** [comment]
Unfortunately their are many conflicts in mechanics_io that must be solved at each merge or rebase. Trying to narrow down the problem, I made two rebases one that works https://github.com/bremond/siconos/tree/mechanics-occ-fix2
one that fails https://github.com/bremond/siconos/tree/mechanics-occ-fix1

So now I can state that the problem is within those commits:

4ff6de6b6 * [examples] add examples of CouplerJointR.
b25c5d0ab * [mechanics] fix one-DS case in CouplerJointR.
5bcb1e1a8 * [examples] fix python examples that use PrismaticJointR.
7efe15f3d * More spelling mistakes found by lintian.
7d9b1b377 * [externals] remove renderer js and replace with npm dependencies
04cd77c1f * [org] up org file
e3023a090 * [cmake] make renderer install optional
2aadf80ab * [numerics] one more spelling unkown -> unknown
635e76f8b * [examples] fix StepSystem script hashbangs
e2e078170 * [examples] Remove windows Thumbs.db
1edf92874 * Fix some spelling mistakes caught by lintian.
d7c32b9c7 * [org] document testing examples
66b1a171c * [cmake] make it possible to compile an individual component as static
d24169537 * [cmake,swig] set SONAME for libraries and swig modules
8760cd50a * [org] minutes of Inria Chile meeting
d67d26f94 * [Changelog] note some kernel and mechanics changes since 4.0.0
6a97daefa * [Changelog] my part of the Changelog
7a57ec60e * [numerics] fix in tlsdef
ac61b92b5 * [mechanics] add cast_ContactR function in base.i
476bfbb31 * [ChangeLog] continue to update ChangeLog
dee2a6898 * [io] add PYTHON_EXECTABLe in vview.py for multiple python installation
1b0d19d2f * [examples] python3 compliant
9b94d4ca2 * [ChangeLog] start to update for 4.1
98019f83a * [CI] set DEV_MODE_STRICT
25d341170 * [mechanics] Enhance CouplerJointR to take a reference body, with examples.
015f782b9 * [kernel] method to set vectors of a BlockVector
9a096d1b3 * [mechanics] Add CouplerJointR and example of a screw constraint.
29532c18b * [mechanics] fix bug in CyclindricalJointR initialization and expose twistCount()
8ff5e4d0d * [mechanics] Fix bad doxygen tag in JointFrictionR.cpp
6c1031c81 * [mechanics] fix empty constructor for PrismaticJointR
9c674a521 * [mechanics] Support absolute frame for PivotJointR vector.
77a744dcc * [mechanics] Fix KneeJointR G1P0/G2P0 calculations for initial orientation.
55a9e08f6 * [swig] Add in/out typemaps for VectorOfVectors.
999f56d5c * [mechanics] Fix missing virtual destructor warning for BulletR.
6b77a7e49 * [mechanics] Rename NewtonEulerJointR::setInitialConditions to setBasePositions.
de7efd0c6 * [mechanics_io] Support for more points/axes, use empty JointR constructors.
6c963968f * [mechanics] Fix some issues creating uninitialized joints.

**Comment by bremond** [comment]
ok, if I am right, reverting this commit alone: 77a744d  makes it work again, even in the master!
Now, it is not obvious for me to see what is going wrong from the commit patch, @radarsat1 do you have any idea ? The slidercrank in mechanism is not affected so there must be some differences when we comes from mechanics_io and c++ (MBTB)

**Comment by radarsat1** [comment]
It appears that in `bodydef.py` the absolute positions of joint anchor points are given and in `MBTB_PYTHON_API.cpp` these are transformed to positions relative to the centers of mass and passed to PivotJointR as relative ds1 coordinates.  So I have done the same in `occ_slider_crank.py` and it works for me.  Please check and close this if it's fixed now.

However, I had to set the anchor point of joint2 to `[[l1+l2, 0, 0]]`.
So I don't understand why bodydef.py contains:

```
jointPos = np.array([(0, 1, 0, 0.0, 0, 0.),
                     (0, 1, 0, l2, 0., 0.),
                     (0, 1, 0, l1, 0., 0)])
```

instead of
```
jointPos = np.array([(0, 1, 0, 0.0, 0, 0.),
                     (0, 1, 0, l1+l2, 0., 0.),
                     (0, 1, 0, l1, 0., 0)])
```

**Comment by bremond** [comment]
Ok it works and with the absolute flag it is clear now for the user. For the difference with mechanisms, maybe the relative positions of the part1 and part2 shapes are different, I haven't check. Anyway we have a fairly complete example with occ, plugins and boundary conditions that is running now with the new API.

**Comment by radarsat1** [comment]
Yes one thing I did with the joints was add the same "absolute" parameter to all joints, since I found it confusing that sometimes it was absolute and sometimes relative, depending on the joint.  In mechanics_io it defaults to True, in C++ it must be specified when creating a joint, or defaults to true in the case of constructing an uninitialized joint.

We could potentially make it required to be specified in `addJoint()`, to be absolutely clear to the user.  Currently addJoint has some arbitrary defaults such as default points and axes and even joint type defaults to PivotJointR.
