### ISSUE TITLE
Updating documentation

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#224]
This issue replaces the two issues #31 and #215 and contains a more general discussion on the documentation.

For the next release (4.2), the only missing work is to update the documentation with the new API. More generally, the documentation is a mess and I propose that we discuss a bit how to refactor it in the issue.

The most urgent step is to reorganize and to update the documentation rather than to write new ones

**Comment by vacary** [comment]
Tools and format for documentation
------------------------------------
 We use several tools for writing and generating documentation:
- doxygen for C++ code
- python docstring for Python code
- rst files and sphinx for user and developper doc
- ipython notebook for some examples and tutorials.
- latex for mathematical docs and developper notes 
- doxy2swig 

Should we reduce the number of formats ?

**Comment by xhub** [comment]
I agree that we need to refactor and update the documentation more than write new parts. Besides getting the online documentation up-to-date, I would like to push for the publication of a new manual technical report in the next months. Ideally we could share the effort and reuse much of the material from one to the other.

That would be lead to see which format is best. I believe that each format you listed have its purpose and can't be substitute for another format completely:
- doxygen is best for the c/c++ function and data structure documentation.
- docstrings is the way to go for python (and there should be only a few of python-only function, the rest is provided by doxy2swig)
- latex is unbeatable for any math heavy part
- doxy2swig is great because it enable us to leverage the doxygen doc and use it in python, removing the need to duplicate a lot of code. It may be fragile, but I see it as a very valuable tool.

An area where we could improve is reusing the description of the concept like LCP, VI, NewtonEuler, ... I think it's a good idea to try to provide a small description of those concept in the doxygen doc and in the manual. It would be great to be able to reuse this text in both, rather than duplicating it. In the manual, we would provide a longer description. In doxygen we could use an "\include" or "\includedoc" command to include an external file that contains the small description. That description would be translated into RST and reuse in the manual via a script. We just have to see what is the best pipeline here, whether it is doxygen-> rst or markdow -> doxygen + markdown -> rst or ... ?

Also I like the idea of reusing part of the online user manual in the pdf user manual or TR. There is an export from rst to latex and we should do our best to leverage that.

**Comment by xhub** [comment]
I've create #228 for improving doxy2swig
