### ISSUE TITLE
improve doxy2swig

### ISSUE THREAD

**Issue by xhub** [siconos/siconos#228]
There has been some interest in improving doxy2swig: https://github.com/m7thon/doxy2swig

@bremond Do we have a list of improvements or fixes to be done?

**Comment by bremond** [comment]
I added this more complete version of doxy2swig generator in 6e6c7a682 and I reported the do_formula stuff from our old one to display maths. I also disabled the autodoc feature from swig (in start.i) because it generates some weird signatures compared to what we can have from those docstrings generated from doxygen.
What is missing for the moment : 
 - removall of  all SP:: and *  
 - the move of all 'usage' parts from python API documentation to user doc.

Note that swig is working on doxygen doc generator for swig 4.0: https://github.com/swig/swig/wiki/SWIG-4.0-Development so maybe this doxy2swig will be replaced one day...

**Comment by vacary** [comment]
Do you have a look how pythonocc is doing? The use swig wrapper over the one library and they are able produce nice doctring documentation.

**Comment by xhub** [comment]
I think they are doing it manually: in https://github.com/tpaviot/pythonocc-core/blob/master/src/Addons/Addons.i

```
%feature("compactdefaultargs") text_to_brep;
%feature("autodoc", "	* Creates a shape of the given text. 
	:param text_to_render: Text to render
	:type text_to_render: char *
	:param aFontName: Font name
	:type aFontName: char *
	:param aFontAspect:  Fontaspect, Font_FA_Regular, Font_FA_Bold, Font_FA_Italic or Font_FA_BoldItalic
	:type aFontAspect: Font_FontAspect
	:param aSize: Size of the font
	:type aSize: float
	:param isCompositeCurve:
	:type isCompositeCurve: bool
	:rtype: TopoDS_Shape
") text_to_brep;
```

**Comment by bremond** [comment]
on origin/update_doc branch doxy2swig is updated and the python API documentation is the one built with apidoc target now. Some bad rendering of maths remain and the SP:: also, I close for 4.2
