### ISSUE TITLE
move occ under collision

### ISSUE THREAD

**Issue by bremond** [siconos/siconos#234]
As everything under occ is about collision, occ module should be under collision module.
I propose to move the C++ part and python part under respective collision directories, do you agree ?

**Comment by radarsat1** [comment]
You are right, but on the other hand I expected "collision" to contain modules that use SiconosCollisionManager/SiconosShape, etc.  I wanted to put all the "native" implementation under that framework (even 2D, e.g. SiconosDisc, SiconosRectangle, etc.) but I do not think I will have time.  So that's okay, it's ok to move occ in there if you think it's better categorized that way and we can figure out whether or not to adapt it to SiconosCollisionManager another time.  Another possibility is to eliminate "collision" and move everything up one directory.  I don't think it's really urgent though, things are "working" right now.  Maybe do it in a branch and see if it really seems strongly better that way?
