### ISSUE TITLE
workVector not initialized when using MatrixIntegrator

### ISSUE THREAD

**Issue by xhub** [siconos/siconos#249]
Recent changes (earlier this month) introduced a regression with the way the MatrixIntegrator works. 
I was able to run it smoothly earlier this month, when I committed the changes for the Twisting-based controllers. Rather than a segfault, I added an assert to make the issue visible:

kernel/src/simulationTools/LsodarOSI.cpp:181: void LsodarOSI::computeRhs(double, DynamicalSystemsGraph&): Assertion `_dynamicalSystemsGraph->properties(*dsi).workVectors' failed.

The tests for MatrixIntegrator got disabled by the changes to conditionnally compile the tests only if there is a FORTRAN compiler. Hence, this issue was not clearly visible.

**Comment by vacary** [comment]
It seems that is related to the commit  8e27c698c6d636de733d8aa7089ee59c6b808964
Revert "[kernel] fix bug with non-initalized interactions" 

I observe also the same when I simulated granular materials. @radarsat1 reverted my commit and I really want to apply it again :-) 

Conclusion:  we have to discuss of what happens.

**Comment by radarsat1** [comment]
The problem seems to be in `LsodarOSI::initialize()`, which needs the variable `_xWork` to already be initialized.  I found that BouncingBallED.cpp is also crashing in the same place as `TwistingTest::test_Twisting_ZOH`.  This function `LsodarOSI::initialize()` is called from `Simulation::initializeIndexSets()`, which is called from `Simulation::initialize()`.  However, `_xWork` is not initialized until `LsodarISO::initializeWorkVectorsForDS` is called, which happens in `Simuiation::initializeNSDSChangeLog`, which is called _after_ initializeIndexSets.

If I change the top of `Simulation::iniitalize` from,
~~~C++
  // 1 - Process any pending OSI->DS associations                                                    
  initializeOSIAssociations();

  // 2 - Initialize index sets for OSIs                                                              
  initializeIndexSets();

  // 3 - allow the InteractionManager to add/remove any interactions it wants                        
  updateWorldFromDS();
  updateInteractions();

  // 4 - initialize new ds and interactions                                                          
  initializeNSDSChangelog();
~~~

to,
~~~C++
  // 1 - Process any pending OSI->DS associations                                                    
  initializeOSIAssociations();

  // 3 - allow the InteractionManager to add/remove any interactions it wants                        
  updateWorldFromDS();
  updateInteractions();

  // 4 - initialize new ds and interactions                                                          
  initializeNSDSChangelog();

  // 2 - Initialize index sets for OSIs                                                              
  initializeIndexSets();
~~~

It fixes both `BouncingBallED` and `TwistingTest::test_Twisting_ZOH`, because `LsodarOSI::_xWork` gets initialized before it is needed.

However, I am not sure of the correctness of this fix, so I haven't committed anything.  That is, it works, but I am not sure if that's the right place to fix it, or if LsodarOSI should be fixed instead.

**Comment by xhub** [comment]
I don't have a strong opinion about that. However, I feel like we could remodel LsodarOSI. I vaguely remember that we wanted to allow for multiple DS to be integrated by the OSI? There is that comment

> TODO FP: use buffer in graph for xWork?

In LsodarOSI::initializeWorkVectorsForDS.

What needs to be done is having a mechanism to prepare some of the integrator data for integrating the DS (setting _intData[0] and _xtmp?) in the graph.

On the other hand, this requires quite some work since all the calls to integrate and logic in EventDriven has to be changed. We could iterate over the DS in the graph, get the OSI this way and call integrate with an additional argument (the ds in the DynamicalSystemsGraph::VDescriptor format) to perform the integration.


In the mean time, I have a fix in master

**Comment by vacary** [comment]
Hi,
It seems that it is working now.
How the bug has been fixed ?

**Comment by xhub** [comment]
I'm closing this since it does not occur anymore.
