### ISSUE TITLE
About inertia of objects with Bullet Contactors

### ISSUE THREAD

**Issue by bremond** [siconos/siconos#263]
With python mechanics_io and Bullet contactors, if inertia was not given at the add_object level, we had an implicit computation of inertia, due to the fact that python object None was mapped to a null SimpleMatrix shared pointer.
This implicit computation is done at each time step (updateContactorInertia, with bullet ), from the fact that BodyDS.setUseContactorInertia is set to true at the construction if inertia is not given.
Now, from c6ec73960, the mapping is not done anymore (we discussed this with @vacary and we agree that these kind of type mapping, None to null pointer, is very, very dangerous as it may occur in situation where it is not wanted). So this implicit inertia computation is not done and the simulation from master branch ends at the moment with a failure in those cases, see for example cube.py.
What solution is preferable:
- leave it like this, and force the user to provide an inertia matrix. Note that this breaks the compatibility and this means to rewrite the examples. the setUseContactorInertia becomes useless (correct me if I am wrong).
Also this means to provide an API hook to calculate inertia before add_object. For occ the inertia is implictly computed if some Volume objects are specified at the same place of the Contactor objects, but what can be done directly with Bullet is not as general as what can be done with OpenCascade.
- if the inertia is not given, print some warning about the implicit calculation and compute the inertia before the BodyDS creation by the same bullet call as the one in updateContactorInertia. Again this means that setUseContactorInertia becomes useless.
- if the inertia is not given, print some warning, build a null shared pointer on SimpleMatrix and pass it at BodyDS creation (or find another way to get the same result). In this case, we get nearly what we had before, but we know why.
- another solution ?

**Comment by vacary** [comment]
I definitively vote for the second options without a warning. The computation of Inertia in bullet is somehow weird. It returns the principal inertia coefficients but we need also the principal axis of inertia. With the principal axis of inertia we have to pre-rotate the system such that the body fixed frame corresponds to the principal inertia axis. Otherwise, NewtonEulerDS consider that the material frame at t=0 in the body fixed frame

Again, we need to introduce markers for bolies and joints to clarify the API. If we do that, we will need to update the Gazebo interface.
