### ISSUE TITLE
Travis build is in errored. 

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#303]
Travis build is in "errored" meaning the build cannot not be completely for an unknown reason after the 20% of compilation.

**Comment by fperignon** [comment]
yeah, it stops after a while, with the message « no output has been received in the last 10 mn ».
The solution is to turn to verbose mode, then it works … but fails later because of « The job exceeded the maximum log length, and has been terminated »
Well, we just have to find the proper verbosity for siconos build
