### ISSUE TITLE
A safe version of `strtok` should be `strtok_s` on Windows.

### ISSUE THREAD

**Issue by wangkuner** [siconos/siconos#349]
The function `strtok_r`, invoked in `numerics/src/tools/CSparseMatrix.c`, is callable on linux system. On Windows, it should be `strtok_s`.

**Comment by xhub** [comment]
Can you try the following fix: at the beginning of `numerics/src/tools/CSparseMatrix.c` (like before `#if defined(__cplusplus)`), add
```
#if defined(_MSC_VER)
  #define strtok_r strtok_s
#endif
```

This would break with C11, since the latter defines another strtok_s. A proper fix would need to check that case as well.

Out of curiosity, which compiler are you using? MSVC (cl.exe) or Clang (clang-cl.exe)?

**Comment by wangkuner** [comment]
I'm using MSVC. I finished compilation by substituting all `strtok_r` with `strtok_s`.

**Comment by xhub** [comment]
Cool! I did some effort compiling siconos on Windows many years back.

Did you compile all of siconos or just numerics?

**Comment by wangkuner** [comment]
Just the externals and numerics
