### ISSUE TITLE
Question: ACEF available?

### ISSUE THREAD

**Issue by gkovacsds** [siconos/siconos#352]
Hello Developers,
we're looking for the ACEF and SpiceImport modules mentioned in the book by Vincent Acary, Olivier Bonnefon, Bernard Brogliato.

Is it available for one of the available Siconos releases? 
Or for any release, with source code?

Thank you.

**Comment by vacary** [comment]
Hi,
Sorry for the delay in my answer. 
ACEF has never ben distributed with Siconos. With Siconos, you can only simulate very simple electrical circuits.
The ACEF code has also never been maintained since 2010. To use or run it, you need to install a very old version of siconos  that is is not easy to do due to the dependance.
If you are still interested in, contact me on my professional email and we can see if it is possible to find a solution either by using an old image of ubuntu or by trying to update ACEF with the new version of siconos.
Best

**Comment by vacary** [comment]
Acef is now available under Apache Licence here
https://github.com/siconos/acef
