### ISSUE TITLE
[mechanics][contact detection] How to control the contact detection of bullet

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#37]
I use the following example to simulate few cubes into an hopper (https://github.com/siconos/siconos/commit/b39650832419828caa668c20de72ae0899757dbc)

I have to question about the control of the contact detection of Bullet 
1 - Is it possible to adjust for Scions/Mechanics the alert distance that creates a contact point between objects?
2- Is it possible to change  or to control the spatial  distribution of contact points between two surfaces ?

**Comment by vacary** [comment]
Is this function the right one for the first question ?

  /** set close contact parameter
   *  \param threshold double value that will be multiplicated by the
   *         radius of the object bouncing box
  */
  void setCloseContactFilterParam(double threshold)
  {
    _closeContactsThreshold = threshold;
  }

**Comment by radarsat1** [comment]
We discussed it at length of course, but I'll summarize here briefly what we found and close,

- gContactBreakingThreshold controls "warning" of contact, but only for btConvexHullShape objects.  Does not work for btBoxShape, btSphereShape.
- The btConvexHullShape contact points are on the *outside* of the margin set by setMargin(), whereas the effect of setMargin() on btBoxShape and btSphereShape is *inside*.  Importantly, the "real" shapes must _never_ overlap, or the GJK convex-convex algorithm gives bad results.  The margins must be selected so that only the margins overlap.  This implies that btConvexHullShape objects should be *shrunk* so that the setMargin() margin leads to an object of the intended size.
