### ISSUE TITLE
Question: relay osnspb / Second Order Sliding Mode Observer

### ISSUE THREAD

**Issue by alex89ctrl** [siconos/siconos#371]
Dear Siconos-Team, 

I have installed Siconos a few weeks ago with the intention to use it for simulating second order sliding mode observers. I started with the examples of conventional sliding modes and the twisting algorithm. Finally, I tried to implement the simulation of generalized super-twisting algorithm. Actually, I ran into some questions that I would like to post here, appreciating any help and comments. 

### Systems structure:
The structure of the considered systems is summarized in the attached file ([SystemStructure.pdf](https://github.com/siconos/siconos/files/5672830/SystemStructure.pdf)). The test system 1 is a second order integrator with the nonlinear observer injection according to the generalized super-twisting algorithm. The test system 2 has order 7 and a more general nonlinear structure. 
### Implementation: 
The test system 1 was implemented as relay problem: 

- FirstOrderLinearDS 
- FirstOrderNonLinearR (with appropriate plugin functions)
- RelayNSL 
- TimeStepping
- Relay osnspb (solver: SICONOS_RELAY_LEMKE)
- EulerMoreauOSI 

The test system 2 was implemented identically, except that a FirstOrderNonLinearDS was used. 
### Results: 

- The simulation of the test system 1 seems to run as assumed and yields results as expected. 
- The simulation of test system 2 does not yield the expected results. That is why I am wondering if my implementation is correct and does make sense. 
### Questions: 

- Has anybody simulated second order or higher order sliding mode algorithms with Siconos? 
- Does the system structure fit a Siconos relay problem? I am not sure if a general FirstOrderNonLinearR is compatible with the relay problem. The relay problem seems to be solved as LCP. Does Siconos cast the relay problem into a MLCP or NCP if necessary? 
- The derivative of the function g(x,lambda) with respect to x (necessary in the nonlinear relation) is singular at the origin. Which smoothness properties are necessary for the function g(x,lambda). 

I do not have enough knowledge on complementarity problems and thus not sure if I am on a wrong path. I would appreciate any help and comments on this topic. 

Thank you very much in advance!

Regards, 
Alex

**Comment by xhub** [comment]
Alex,

Thanks for the report. I will have a look at it next week. Thanks for typing down the system. I believe there is an inconsistency between (5) and (6). Could you please fix it to remove any ambiguity?

I have implemented a Twisting controller in siconos.

**Comment by alex89ctrl** [comment]
I fixed equations (5) and (6), slightly changed the notation and added the dimensions of the pseudo-inverse in the last paragraph. Thank you very much for having a look at it. If there are any further questions, please contact me. The updated file: 
[SystemStructureUpdated.pdf](https://github.com/siconos/siconos/files/5678050/SystemStructureUpdated.pdf)

**Comment by vacary** [comment]
Any updates?

**Comment by alex89ctrl** [comment]
Not from my side at the moment. I will work on the topic again starting next week.

**Comment by xhub** [comment]
Alex,

I looked a bit at the problem formulation of problem 1. The system is a bit challenging to solve since the RHS contains continuous, but not differentiable terms. Indeed, all the terms involving a power of |x| multiply by lambda are continuous. The only discontinuous term is (mu_1)^2 * λ / 2. It is also the simplest one to deal with. It is not especially well written, but we require all functions to be differentiable, to linearise the problem, see https://nonsmooth.gricad-pages.univ-grenoble-alpes.fr/siconos/reference/cpp/kernel/classFirstOrderNonLinearR.html?highlight=firstordernonlinearr

In the provided formulation, the function `g` is not differentiable with respect to `x`. Depending on how the jacobian is defined, the system might be numerically solvable for some given initial point. All kind of guarantees are unfortunately gone.

The first idea is to change the RHS of (1) by substituting  λ with `-sgn(-x_1)` in all the continuous terms. This leaves just λ multiplied by a constant in the RHS of (1.2). I would also change the definition of λ to be `λ\in sign(-x_1)`. This enables us to invert it to `-x_1 \in N_{[-1,1]}(λ)`, where `N_{[-1,1]}` is the normal cone operator to the set `[-1,1]`.
Then we have in (1) an ODE with a RHS continuous (but not differentiable) in x, and a discontinuous input λ.
To fix notation, we would have
``` \dot{x} = -F(x) - (α, 0)^T λ```
and
```0\in (1, 0) x +  N_{[-1,1]}(λ)```

We can then discretize implicitly the first relation of this system, which gives
```
x^{k+1} - x^{k} + hF(x^{k+1}) + h(α, 0)^T λ^{k+1} = 0
0\in (1, 0) x^{k+1} +  N_{[-1,1]}(λ^{k+1})
```

This is actually a Variational Inequality in `(x^{k+1}, λ^{k+1})` over `R^2\times [-1,1]`, that is just simple bounds (box constraints). The functional part being continuous but not differentiable, Newton-type methods cannot be applied a priori. This leaves the "Projection Methods", like ExtraGradient.

It seems to me like one needs to forgo the kernel modelling layer, and directly use the solvers in numerics. @vacary can double check, but it appears to me that `FirstOrderNonLinearDS` require the RHS to be differentiable with respect to the state `x`. The system under consideration would not fulfill this assumption.

One would need to directly use the numerics layer and specify the VI directly, with a small loop to integrate forward in time. This is what is done for the Zhuravlev-Ivanov examples. One can also look at `test_vi_3D` and `test_vi_C_interface` in `numerics/swig/tests/test_vi.py` for inspiration.

Note that a small coding task must be performed to solve this system, namely to implement how to solve a box-constrained VI using the ExtraGradient method. If you are interested in that, I can quickly code that up. Note that the convergence theory requires some (pseudo)-monotonicity, which might be fulfilled here, but I didn't check that. The book by Fiacchinei and Pang has some details in Chapter 12.

There are also other approaches, like trying to check whether a custom semismooth newton method could be designed, or to try to model the continuous but not differentiable part in a different way. However, this is quite theoretically involved and would likely require custom code.

It might be helpful also at some point to share some code, shoot me an email  if you wish to do so privately.

**Comment by alex89ctrl** [comment]
Olivier, 

thank you very much for providing all the information. I will work through your suggestions, but it will take some time. However, I will stay on this topic and inform you about the results.

**Comment by xhub** [comment]
Alex,

Good to know. Depending on your background, the stuff can be intimidating. If further questions arise, maybe the discussion could also move to another medium than github, especially if some math is involved.
