### ISSUE TITLE
Question on model time vs. simulation time

### ISSUE THREAD

**Issue by radarsat1** [siconos/siconos#60]
I just noticed that in my tests, I added something to print the time and in fact time is not advancing, it is always printing zero.  (Even though the simulation is clearly advancing.)  So I wondered if I am stepping the simulation correctly.  However, looking through the examples, the few that use `model->currentTime()` step the simulation with,

```
_model()->simulation()->advanceToEvent();
_model()->simulation()->processEvents();
```

while the rest use `simulation->nextTime()` to get the time, and step the simulation with,

```
simulation->computeOneStep();
simulation->nextStep();
```

I assume one of these is the "old" way and one is the "new" way, but which is currently recommended?

**Comment by radarsat1** [comment]
ps. I switched from `model->currentTime()` to `simulation->nextTime()` and now everything is fine.  Still wondering what is the recommended approach.

**Comment by vacary** [comment]
This point is interesting. Again, there are multiple ways of managing time in siconos. Perhaps, we have to simplify and to propose only one API

**Comment by radarsat1** [comment]
Personally I think it makes more sense to have time associated with the simulation rather than the model, so I'm fine with the change I had to make.  Might be worth going through and finding where the model is used to get the time and change it for `model()->simulation()->nextTime()`

**Comment by vacary** [comment]
Should we remove time from model ?

**Comment by xhub** [comment]
* Vincent Acary <notifications@github.com> [2016-06-15 05:56:16 -0700]:

> Should we remove time from model ?

I think this is a good idea. The only case I see where we might need the time in the Model is the case when we have multiple simulations for the same NSDS. I heard of this feature a few time, but it is nowhere near being ready (or is it?).

In the mean time, let's kill it.

**Comment by bremond** [comment]
I vote also for the removal.
The need of time for multiple simulations in a object that is devoted to the association
NonSmoothDynamicalSystem + Simulation is really not clear. Why time and
not another part of the simulation state ?

Also, for clarity shouldn't NonSmoothDynamicalSystem be called NonSmoothModel
and Model something like ModelSimulation or ModelInstantiation or
ModelAssociation or ... ?

**Comment by vacary** [comment]
For the time management, the reference time is since one of my commit March the time of the simulation. We can go further and remove time from the model. The only problem is the fact that the value stored in the Model (DS, Interaction ..) could be not synchronize with the time of simulation. This is not really important. I  propose to keep the attributes but to remove the accessor or te obscurify it.


For the second comment of Maurice, for Model is something on top of NonSmoothDynamical system and Simulation. A numerical Model is mathematically speaking a representation of a real system together with a numerical techniques to solve it. I propose Model -- > NumericalModel but i do not think that it is necessary

For me, the Model is not only the equation and the formulation.
