### ISSUE TITLE
deprecated keyword and gcc < 4.5

### ISSUE THREAD

**Issue by fperignon** [siconos/siconos#73]
It seems that call to 'deprecated(msg)'  with msg attribute  is only available for gcc >= 4.5.
This is used in Model.hpp and my compilation failed because of that on Froggy cluster.

What do you think of requiring gcc > 4.5 for siconos?
Or even 4.9 which is I think the debian stable gcc version.

**Comment by radarsat1** [comment]
Regarding compiler support, I think it's best to take a "feature" approach.  Check `cmake/cxxTools.cmake` and `cmake/CXXCompilerSetup.cmake`.  You compile a small bit of code containing "deprecated" and check if it works, use that feature only in that case (e.g. by a macro).

**Comment by xhub** [comment]
FYI we already require GCC >= 4.4 (as seen in CXXCompilerSetup.cmake). I remember that there was an issue with some config that required GCC >= 4.5. We could impose 4.5 at least now

**Comment by vacary** [comment]
Hi
What should we do now with this issue ? Should we ask for Gcc 4.5 ?

**Comment by radarsat1** [comment]
Previously it was done with a macro DEPRECATED_MODEL_API, which could be made compatible for previous versions of gcc, I think.  Would require a bit of testing, but I don't think this issue by itself is exactly the right reason to update the compiler.  There are other reasons of course ;)  But I suggest closing this one for now, it seems fixed.

Note however that if we *don't* update the compiler requirements, I suggest we find a way to test regularly on gcc 4.4 and older.  (Travis?)  Otherwise we will continue to miss things.

**Comment by radarsat1** [comment]
I add this as a milestone for 4.1, since we should decide on what version of gcc to require.

**Comment by vacary** [comment]
Ok, I suggest that we require gcc 4.5 GCC 4.5.0 April 14, 2010.

I will do the modification and I close this issue.
