### ISSUE TITLE
[numerics] convergence problem with openmp

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#78]
openMP version of fc3d_nsgs destabilize the convergence rate. see fc3d_test31

**Comment by radarsat1** [comment]
I found the reason for the problem, and it's not pretty!  :(
Well, fixable, I hope, but it will take some work.

Inside `fc3d_nsgs_computeqLocal()`, called from `fc3d_nsgs_update()`, the `reaction` matrix is used to calculate qLocal, which must skip the current contact.  It does so by setting one row of `reaction` to zero, temporarily.  Then, the whole matrix is used as `x` (read-only) in the operation.

So, since `reaction` is shared, if multiple parallel contact problems are being updated then some of these operations are reading the temporary zeros of the other parallel problems.

I tried fixing it by making a copy of `reaction` for each thread, but this killed performance, and is bad on memory.  I tried a better fix, making a version of `rowProdNoDiagSBM` in `SparseBlockMatrix.c` that skips some specified cells, but this also kills performance, for reasons I don't quite understand.*

Another source of problems is that the solver may execute (writing to `reaction`) at the same time as the problem update is performed in another thread (reading from `reaction`), so possibly a barrier is needed there.  My attempts to fix this so far also seem to kill performance.

* It seems that if there are no *writes* to `reaction` in `fc3d_nsgs_computeqLocal`, the execution speed is back to non-parallel execution speeds.  No idea why.  Probably a compiler optimisation that doesn't kick in.  That is, if I make no other changes than simply commenting out the following lines, everything goes much slower:

```
reaction[in] = 0.0;                                                                    
reaction[it] = 0.0;                                                                    
reaction[is] = 0.0;
```

Weird.

**Comment by radarsat1** [comment]
Note: a fix for dense matrices would be needed too.

**Comment by vacary** [comment]
ok, 

I also remark that if I add a printf in the loop it slows down the thread and the algorithm works. I have the impression that the read/write at the same time in reaction is the source of the problem.

I will ask to an expert : @fperignon

**Comment by vacary** [comment]
I get some segfaults with clang-3.7 on Mac. We still have bad access to memory in solver options. Hope, hope.

**Comment by vacary** [comment]
* The seg faults were only on GlockerNCP formulation. It has to be fixed since there are some global objects 
   * The local problem solver based on local projection is not stable. Something is wrong in the local options
   * The local problem solver based on NSN is working well. Nevertheless, I do not know if the performance is really better for the moment.

 @radarsat1 could you commit your python script for testing performance ?

**Comment by radarsat1** [comment]
It's in d638b5a4036cbe3534b6944658d1cd1709f1e005

**Comment by radarsat1** [comment]
I've been testing this weekend, and I think there is something deeper a bit wrong here.  It seems that even if I disable parallelism, if I change access to `reactions` it changes the behaviour of the solution.  I realized that each contact uses the `reactions` matrix updated from the previous contact.  If I replace this with local memory to receive the changes and "double buffer" the reactions so that all contacts get the same `reactions` matrix, in fact the solution does not converge, but rather explodes into NaNs.  (That is to say, `reactions` is only updated each iteration, but not between contacts.)

It seems that for the computation to converge, it depends on each contact resolution having access to the previous, which seems wrong to me mathematically speaking, since contacts should be independent (in this formulation).  Since they are not, opportunities for parallelism are broken.  Let's look at it together this week.

**Comment by radarsat1** [comment]
Ok after some discussion and reading the [wikipedia page on Gauss Seidel](https://en.wikipedia.org/wiki/Gauss%E2%80%93Seidel_method), I now understand why it can't be done in parallel ;)

So, implementing the Jacobi method or finding other approaches is now on the to-do list.

**Comment by radarsat1** [comment]
Just realized why the speed-up appears to be so much better when the `reaction[in] = 0.0` block is enabled.  It's because the solution is so wrong in that case that the blocks fly apart and there are no more contacts to compute.

**Comment by vacary** [comment]
I fully agree on the fact that Gauss-Seidel is not parallelizable and Jacobi is. This is well known but for me it was only a theoretical question.
In the following, the author proposes a naive implementation of a parallel Gauss Seidel:

http://homepages.math.uic.edu/~jan/mcs572/syncheatdomain.pdf

Why is it not possible to do the same thing ?

Otherwise, the only way is to perform a rigorous domain decomposition by coloring our contact  points with Scotch or metis

**Comment by vacary** [comment]
We can also find a lot of possible coloring or numbering in the PhD Thesis of one of our great master 
https://scholar.google.com/citations?user=HWL0SNgAAAAJ&hl=en

https://tel.archives-ouvertes.fr/tel-00007686/document

page 54 for instance 

or in 

https://scholar.google.com/citations?user=HWL0SNgAAAAJ&hl=en

**Comment by radarsat1** [comment]
Just taking some further research notes.  This paper is interesting [1] and mentions the biconjugate gradient method.  I found a presentation here [2]  where they talk about wanting to integrate it into CNC, which is a software for parallel linear systems solving, Concurrent Number Cruncher.  This note [3] says that it has now been made part of OpenNL [4], which is, surprise surprise, an INRIA software.  So I suppose some Siconos people already know about this ;)

I can't find any reference to biconjugate gradient in there, so I don't know if they ever integrated it, but anyways, could be interesting to look into using such a library, or porting code, or contacting that team for advice.

[1] http://www.metz.supelec.fr/metz/personnel/vialle/information-vialle/publication-repository/Parco2009.pdf
[2] https://www.researchgate.net/publication/230844621_Solveur_lineaire_sur_GPU
[3] http://alice.loria.fr/index.php/software/4-library/34-concurrent-number-cruncher.html
[4] https://gforge.inria.fr/frs/?group_id=1252

**Comment by radarsat1** [comment]
This could be interesting to check out: https://github.com/ddemidov/amgcl

(There is also one by Nvidia, although it's only free with registration, https://developer.nvidia.com/amgx)

Also, https://www.libama.org/overview.html seems like it might have some relevant routines.

This one, not sure it is applicable for parallel, but it seems to have some openmp options in the configuration https://github.com/exasc/lssp/

**Comment by radarsat1** [comment]
Lots of really useful information (detailed) in this paper: http://www.zfm.ethz.ch/~nuetzig/files/projective.pdf

**Comment by radarsat1** [comment]
Now we know the reasons for this and parallelism is an on-going research project, so let's close the "bug"
