### ISSUE TITLE
[numerics] improve computeAWpB in the sparse case

### ISSUE THREAD

**Issue by xhub** [siconos/siconos#92]
the W matrix is symmetric in the fc3d case. Therefore, we can do better when computing this matrix than the classical gemm

**Comment by vacary** [comment]
Yes good idea, but we have to be careful since W is not necessarily a symmetric matrix. We can add a new flag in the NumericsMatrix  (numerics_matrix ?) structure to know if the matrix is symmetric, unsymmetric or undefined.  if is it undefined, we can test it not the fly with a simple numerical test.

**Comment by xhub** [comment]
True I always thing about the rigid body case. And I believe we should we should store some properties like the symmetry, since we may be able to exploit that information.

**Comment by xhub** [comment]
This is low priority, setting a future milestone
